version: '3.8'

services:
  microservice:
    build:
      context: ..
      dockerfile: src/GtMotive.Estimate.Microservice.Host/Dockerfile
    image: vehicle-rental:latest
    container_name: vehicle-rental-api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - vehicle-rental

networks:
  vehicle-rental:
    driver: bridge