version: '3.8'

services:
  microservice-dev:
    build:
      context: ..
      dockerfile: src/Dockerfile.dev
    image: vehicle-rental-dev:latest
    container_name: vehicle-rental-dev
    ports:
      - "5000:5000"
    volumes:
      - ../:/src
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - vehicle-rental-dev

networks:
  vehicle-rental-dev:
    driver: bridge